_: &language_go_1_13
  name: "go 1.13"
  language: go
  go: "1.13.x"
_: &language_go_1_14
  name: "go 1.14"
  language: go
  go: "1.14.x"
_: &language_js
  language: node_js
  node_js: "lts/*"

_: &gen_link_kyber
  pushd external/js/kyber && npm ci && npm run link && popd
_: &get_go
  - gimme 1.13
  - . $HOME/.gimme/envs/go1.13.env

_: &stage_build_go
  script:
    - make -C conode bindist tooldist
    - GO111MODULE=on go build ./...
_: &stage_deploy_npm
  <<: *language_js
  before_deploy: echo "//registry.npmjs.org/:_authToken=${DEPLOY_NPM_TOKEN}" > $HOME/.npmrc
  script: skip  # default to `make test`

dist: trusty

stages:
  - lint
  - build
  - test
  - deploy

jobs:
  include:
    - stage: test
      <<: *language_js
      install: *get_go
      before_script:
        - make docker
        - *gen_link_kyber
      script:
        - cd external/js/cothority
        - npm ci
        - npm link @dedis/kyber
        - npm run test:nocover -- --filter="Inst should"

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
